/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wise.meow.display;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.Timer;
import wise_meow.WiseMeow;

/**
 *
 * @author shuhan
 */
public class DisplayEasy extends javax.swing.JFrame {

    /**
     * Creates new form DisplayEasy
     */
    int flg = 0;

    public DisplayEasy() {
        initComponents();
        OutputField.append("Lara:\n Hi I am lara . I am a wise meow . I am going to be a intelectual partner of you :D \n\n");
        OutputField.append("YOU:\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        InputField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputField = new javax.swing.JTextArea();
        button = new javax.swing.JButton("send");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lara The WISE_MEOW");
        setForeground(java.awt.Color.darkGray);
        setResizable(false);

        InputField.setText("Type a message");
        InputField.setToolTipText("Type A message");
        InputField.setName("Your Message"); // NOI18N
        InputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                String S = InputFieldActionPerformed(evt);

                WiseMeow lara = new WiseMeow();

                InputField.setText("");
                OutputField.append(S);
                OutputField.append("\n");
                OutputField.append("LARA: \n");

                if (flg == 1) {
                    try {
                        Files.write(Paths.get("newChat.txt"), S.getBytes(), StandardOpenOption.APPEND);
                        Files.write(Paths.get("newChat.txt"), "\n".getBytes(), StandardOpenOption.APPEND);

                        Files.write(Paths.get("newChat.txt"), "######################################".getBytes(), StandardOpenOption.APPEND);
                        Files.write(Paths.get("newChat.txt"), "\n".getBytes(), StandardOpenOption.APPEND);

                        S = "Thank you wise human :D";
                        flg = 0;
                    } catch (IOException ex) {
                        Logger.getLogger(DisplayEasy.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {

                    try {
                        S = lara.chat(S);
                    } catch (Exception ex) {
                        try {

                            String str = null;

                            Files.write(Paths.get("newChat.txt"), S.getBytes(), StandardOpenOption.APPEND);
                            Files.write(Paths.get("newChat.txt"), "\n".getBytes(), StandardOpenOption.APPEND);

                            S = "I didn't understand what you told me. Please teach me what to respond in the asked question.Thanks :D";
                            flg = 1;

                        } catch (IOException ex1) {
                            Logger.getLogger(DisplayEasy.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    }
                }

                    OutputField.append(S);
                    OutputField.append("\n\n");
                    OutputField.append("YOU: \n");
                
            }
        });

        OutputField.setEditable(false);
        OutputField.setColumns(20);
        OutputField.setLineWrap(true);
        OutputField.setRows(5);
        OutputField.setWrapStyleWord(true);
        OutputField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(OutputField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InputField)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputField, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private String InputFieldActionPerformed(java.awt.event.ActionEvent evt) {
        return InputField.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayEasy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField InputField;
    private javax.swing.JTextArea OutputField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton button;
    // End of variabes declaration                   
}
